allowBuilds:
  '@parcel/watcher': set this to true or false
  '@tailwindcss/oxide': set this to true or false
  esbuild: set this to true or false
  puppeteer: set this to true or false
  sharp: set this to true or false
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - es5-ext
  - esbuild
  - puppeteer
  - sharp
